### ISSUE TITLE
Latency between reveal and animation when scrolling down

### ISSUE THREAD

**Issue by SebastianBoldt** [anijs/examples#3]
There is little latency between the reveal-action and the actual animation.
If you scroll down, the element first appears on its original position and then animates. 
If you scroll up everything works fine.

Tested on a Macbook Retina, Google Chrome (Version 35.0.1916.153) and Safari (Version 7.0.5)

**Comment by darielnoel** [comment]
Hello Sebastian, thanks for sharing, if you want remove the little latency between the reveal-action and the actual animation you need to overwrite the default scrollReveal function behavior. Please go to the **anijs-helper-scrollreveal.js** file and take a look to this line: 

``` javascript
if (ScrollRevealHelper.isElementInViewport(element, 0.33)) {
```

You can change the factor value to 0 if you don't want latency.

``` javascript
if (ScrollRevealHelper.isElementInViewport(element, 0.0)) {
```

In the near future we would to add this feature without you can change the original code, but by the moment it's the solution.

Best Regards, Dariel
